apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  labels:
    k8s-app: fluent-bit-logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush 1
        Daemon Off
        Log_Level info
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        storage.path              /var/log/flb-storage/
        storage.sync              normal
        storage.checksum          off
        storage.backlog.mem_limit 50M

    [INPUT]
        Name             tail
        Tag              kube.*
        Path             /var/log/containers/*.log
        Parser           docker
        DB               /var/log/flb_kube.db
        Mem_Buf_Limit    50MB
        Skip_Long_Lines  On
        Refresh_Interval 10

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On*

    [FILTER]
        Name modify
        Match *
        Rename message content
        Rename log content

    [FILTER]
        Name            kubernetes
        Match           kube.*
        Kube_URL        https://kubernetes.default.svc
        Merge_Log       On
        Merge_Log_Trim  On
        Labels          Off
        Annotations Off
        K8S-Logging.Parser Off
        K8S-Logging.Exclude Off

    [FILTER]
        Name         nest
        Match        kube.*
        Operation    lift
        Nested_under kubernetes
        Add_prefix   kubernetes_

    [FILTER]
        Name grep
        Match kube.*
        Exclude kubernetes_container_name fluent-bit

    [FILTER]
        Name modify
        Match kube.*
        Rename log content
        Rename kubernetes_pod_name k8s.pod.name
        Rename kubernetes_namespace_name k8s.namespace.name
        Remove kubernetes_container_image
        Remove kubernetes_docker_id
        Remove kubernetes_container_name
        Remove kubernetes_pod_id
        Remove kubernetes_host
        Remove time
        Remove kubernetes_container_hash
        Add    k8s.cluster.name Onlineboutique

    [FILTER]
        Name     throttle
        Match    kube.*
        Rate     5000
        Window   5
        Print_Status true
        Interval 30s
    
    [OUTPUT]
        Name http
        Match *
        host ${FLB_HTTP_HOST}
        port ${FLB_HTTP_PORT}
        format json
  parsers.conf: |-
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L

  custom_parsers.conf: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L