apiVersion: v1
kind: Service
metadata:
  name: fluent-bit-svc
  labels:
    k8s-app: fluent-bit-logging
spec:
  ports:
  - port: 2020
    targetPort: http
    protocol: TCP
    name: http
  type: NodePort
